broadinstitute/backstage

catalog-info.yaml, deployment/dev/backstage/Kptfile, deployment/dev/backstage/backstage-service.yaml, deployment/dev/backstage/backstage.yaml, deployment/dev/backstage/gcp-load-balancer/frontendconfig.yaml, deployment/dev/backstage/gcp-load-balancer/ingress.yaml, deployment/dev/backstage/gcp-load-balancer/managedcertificate.yaml, deployment/dev/backstage/hpa.yaml, deployment/dev/backstage/serviceaccount.yaml, deployment/prod/backstage/Kptfile, deployment/prod/backstage/backstage-service.yaml, deployment/prod/backstage/backstage.yaml, deployment/prod/backstage/gcp-load-balancer/frontendconfig.yaml, deployment/prod/backstage/gcp-load-balancer/ingress.yaml, deployment/prod/backstage/gcp-load-balancer/managedcertificate.yaml, deployment/prod/backstage/hpa.yaml, deployment/prod/backstage/serviceaccount.yaml
this should help backstage add a k8s tab
---
=> feat: adding annotation to resources

backstage/app-config.yaml, backstage/templates/BITS/domains.yaml, backstage/templates/BITS/domains/automation.yaml, backstage/templates/BITS/domains/cloud.yaml, backstage/templates/BITS/domains/containers.yaml, backstage/templates/BITS/domains/hpc.yaml, backstage/templates/BITS/domains/infrastructure-tools.yaml, backstage/templates/BITS/domains/monitoring.yaml, backstage/templates/BITS/domains/orchestration.yaml, backstage/templates/BITS/domains/server-operating-systems.yaml, backstage/templates/BITS/domains/virtualization.yaml, catalog-info.yaml, deployment/dev/backstage/backstage.yaml, deployment/dev/backstage/hpa.yaml, deployment/prod/backstage/backstage.yaml, deployment/prod/backstage/hpa.yaml
Misc Small updates, mostly adding Domains so we have a few examples 
---
=> feat: Misc updates to add depth and metadata to the MVP 

backstage/app-config.production.yaml, backstage/app-config.yaml, backstage/examples/template/content/catalog-info.yaml, backstage/examples/template/pagerduty.yaml, backstage/packages/app/package.json, backstage/packages/app/src/App.tsx, backstage/packages/app/src/components/catalog/EntityPage.tsx, backstage/packages/backend/package.json, backstage/packages/backend/src/index.ts, backstage/packages/backend/src/plugins/pagerduty.ts, backstage/packages/backend/src/plugins/scaffolder.ts, backstage/yarn.lock, deployment/dev/.envrc, deployment/dev/backstage/backstage.yaml, deployment/dev/terraform/terraform.tfvars, deployment/prod/.envrc, deployment/prod/backstage/backstage.yaml, deployment/prod/terraform/terraform.tfvars, docs/index.md, docs/plugins.md
This PR  This commit allows us to add a pagerduty annotation to our components - more info can be found here : https://pagerduty.github.io/backstage-plugin-docs/
as well as updates the plugin docs 
---
=> feat: Add PagerDuty plugin

backstage/examples/entities.yaml, backstage/templates/BITS/domains.yaml, catalog-info.yaml
Adding some basic entities to be used by BITS Teams  - Domains to indicate entities and systems that are part of our product offereings 
---
=> feat: Update Metadata and Entitites used by the catlaog

backstage/app-config.production.yaml, backstage/app-config.yaml, catalog-info.yaml
Locations are only loaded by the prod config so needed to move the url localtion over to the prod config! :doh:
---
=> fix: Update app-config.production.yaml and app-config.yaml

backstage/templates/scaffolder/pr-with-catalog-entry/content/catalog-info.yaml, backstage/templates/scaffolder/pr-with-catalog-entry/template.yaml, backstage/templates/scaffolder/terraform-control-module/content/catalog-info.yaml, backstage/templates/scaffolder/terraform-control-module/template.yaml, backstage/templates/scaffolder/terraform-with-terragrunt/content/catalog-info.yaml, backstage/templates/scaffolder/terraform-with-terragrunt/template.yaml
=> feat: Update catalog-info.yaml with dynamic values

backstage/templates/scaffolder/terraform-control-module/content/atlantis.yaml, backstage/templates/scaffolder/terraform-control-module/content/dev/variables.tf, backstage/templates/scaffolder/terraform-control-module/content/prod/locals.tf, backstage/templates/scaffolder/terraform-control-module/content/prod/main.tf, backstage/templates/scaffolder/terraform-control-module/content/prod/variables.tf, backstage/templates/scaffolder/terraform-with-terragrunt/content/atlantis.yaml
Fixing missing files and directories in the terraform template 
---
=> fix: update terraform templates to fix missing files and dirs

backstage/templates/BITS/systems.yaml, backstage/templates/BITS/systems/hpc-comm.yaml, backstage/templates/BITS/systems/hpc-drag.yaml, backstage/templates/BITS/systems/seqprod.yaml
Adds some HPC Related Systems to backstage which will let ys connect some of the components we are creating back to our product offerings (Domains) 
---
=> chore: Add HPC clusters as backstage systems

.pre-commit-config.yaml, deployment/dev/backstage/Kptfile, deployment/dev/backstage/backstage-service.yaml, deployment/dev/backstage/backstage.yaml, deployment/dev/backstage/gcp-load-balancer/Kptfile, deployment/dev/backstage/gcp-load-balancer/frontendconfig.yaml, deployment/dev/backstage/gcp-load-balancer/ingress.yaml, deployment/dev/backstage/gcp-load-balancer/managedcertificate.yaml, deployment/dev/backstage/gcp-load-balancer/package-context.yaml, deployment/dev/backstage/hpa.yaml, deployment/dev/backstage/package-context.yaml, deployment/dev/backstage/serviceaccount.yaml, deployment/prod/backstage/Kptfile, deployment/prod/backstage/backstage-service.yaml, deployment/prod/backstage/backstage.yaml, deployment/prod/backstage/gcp-load-balancer/Kptfile, deployment/prod/backstage/gcp-load-balancer/frontendconfig.yaml, deployment/prod/backstage/gcp-load-balancer/ingress.yaml, deployment/prod/backstage/gcp-load-balancer/managedcertificate.yaml, deployment/prod/backstage/gcp-load-balancer/package-context.yaml, deployment/prod/backstage/hpa.yaml, deployment/prod/backstage/package-context.yaml, deployment/prod/backstage/serviceaccount.yaml
this addresss this ticket https://broadbits.atlassian.net/browse/BCTC-182
So many changes due to the yaml linter... :sigh: 
I changed it to match the .pre-commit file that Atlantis uses, which should be slightly more sane in the future. 
---
=> feat: Update SSL Policy In Frontend

backstage/templates/scaffolder/terraform-storage-transfer/content/docs/usage.md
Users might be running windows smh
=> fix: Add windows command for base64 decode

atlantis.yaml, deployment/dev/terraform/.terraform.lock.hcl, deployment/dev/terraform/README.md, deployment/dev/terraform/database.tf, deployment/dev/terraform/terraform.tf, deployment/prod/terraform/.terraform.lock.hcl, deployment/prod/terraform/README.md, deployment/prod/terraform/database.tf, deployment/prod/terraform/terraform.tf
This PR closes #57 and #58
---
=> chore: Update Google Cloud SQL connectors to version 2.12.0

backstage/packages/backend/package.json, backstage/packages/backend/src/instrumentation.js, backstage/yarn.lock, deployment/dev/backstage/backstage.yaml, deployment/dev/backstage/monitoring.yaml, deployment/prod/backstage/monitoring.yaml
Adding Open Telemtry so that we can scrape metrics from the backstage app. 
---
=> feat: Add OpenTelemetry instrumentation for backend service

backstage/project.toml
Explicitly add the correct builders in the projects descriptor file
---
=> fix: Explicitly add the correct builders  in project.toml

backstage/app-config.production.yaml, backstage/templates/scaffolder/add-spack-package/content/spack/packages/package.yaml, backstage/templates/scaffolder/add-spack-package/template.yaml
This will close out BITSDN-3900
---
=> feat: add Spack package scaffolder template and configuration

.github/workflows/schedule.yaml
Setting a 60 days limit on issues and PRs before they are marked stale and closed
---
=> feat: add scheduled workflow to close stale issues and PRs

backstage/packages/app/src/App.tsx
This allows  Terraform and Python Software templates to be
grouped together  on the /create page
---
=> feat: add filters to Software Template

.github/dependabot.yml
Make dependabot suggest updates for backstage *gulp*
---
=> chore(dependabot): add npm update config

.github/dependabot.yml
Backstage doesn't support above react 18
---
=> chore: ignore major version updates for React

backstage/app-config.production.yaml, backstage/templates/BITS/domains.yaml, backstage/templates/BITS/domains/erp.yaml, backstage/templates/BITS/systems.yaml, backstage/templates/BITS/systems/sap.yaml, backstage/templates/BITS/systems/scisoft.yaml
Adding System and Domains for SAP and ERP to the software catalog
---
=> feat: add ERP and SAP to catalog

deployment/dev/terraform/README.md, deployment/dev/terraform/database.tf, deployment/dev/terraform/terraform.tfvars, deployment/dev/terraform/variables.tf, deployment/prod/terraform/README.md, deployment/prod/terraform/database.tf, deployment/prod/terraform/terraform.tfvars, deployment/prod/terraform/variables.tf
Bumped the postgres and SA modules and moved all the data into tfvars
file so it's standard
---
=> chore(terraform): modules update and refactor

.github/release.yaml, backstage/templates/scaffolder/add-namespace/template.yaml, backstage/templates/scaffolder/add-spack-package/template.yaml, backstage/templates/scaffolder/pr-with-catalog-entry/template.yaml, backstage/templates/scaffolder/python-package/content/.github/CODEOWNERS, backstage/templates/scaffolder/python-package/content/.github/workflows/checks.yaml, backstage/templates/scaffolder/python-package/template.yaml, backstage/templates/scaffolder/terraform-control-module/content/.github/CODEOWNERS, backstage/templates/scaffolder/terraform-control-module/content/.github/workflows/checks.yaml, backstage/templates/scaffolder/terraform-control-module/template.yaml, backstage/templates/scaffolder/terraform-storage-transfer/content/.github/CODEOWNERS, backstage/templates/scaffolder/terraform-storage-transfer/content/.github/workflows/checks.yaml, backstage/templates/scaffolder/terraform-storage-transfer/template.yaml, backstage/templates/scaffolder/terraform-with-terragrunt/content/.github/CODEOWNERS, backstage/templates/scaffolder/terraform-with-terragrunt/content/.github/workflows/checks.yaml, backstage/templates/scaffolder/terraform-with-terragrunt/template.yaml
=> fix: Misc Scaffolder Fixes

backstage/packages/app/package.json, backstage/packages/app/src/App.tsx, backstage/packages/app/src/components/Root/Root.tsx, backstage/packages/app/src/components/home/HomePage.tsx, backstage/yarn.lock
Adding a first pass at a default landing page for backstage
---
=> feat(): Add default home page

.cloudbuild/build.yaml, backstage/package.json, backstage/packages/app/package.json, backstage/packages/app/src/App.tsx, backstage/packages/app/src/components/catalog/EntityPage.tsx, backstage/yarn.lock, docs/techdocs.md, docs/terraform.md, mkdocs.yml
Allows users to add Mermaid diagrams to markdown pages with `mermaid` block
for example:
```mermaid
---
query: architecture diagram
references:
- "File: /Untitled-2"
- "File: /deployment/dev/terraform/locals.tf"
- "File: /deployment/dev/terraform/team-access.tf"
- "File: /deployment/dev/terraform/terraform.tf"
- "File: /deployment/dev/terraform/variables.tf"
- "File: /deployment/dev/terraform/README.md"
generationTime: 2025-04-16T14:51:23.702Z
---
flowchart LR
subgraph Google Cloud Platform
direction TB
A1["API Services<br>google_project_service.api_services"]:::resource
A2["Secret Manager<br>google_secret_manager_secret.backstage-bits-credentials"]:::resource
A3["Secret IAM Member<br>google_secret_manager_secret_iam_member.ksa-access"]:::resource
A4["Tech Docs …
```
=> feat: Add Mermaid support in TechDocs

docs/kube.mmd, mkdocs.yml
=> docs: Adding diagram of the kube deployment

.github/workflows/checks.yaml, backstage/app-config.production.yaml, backstage/templates/scaffolder/add-namespace/template.yaml, backstage/templates/scaffolder/add-spack-package/template.yaml, backstage/templates/scaffolder/terraform-cloud-run/template.yaml, backstage/templates/scaffolder/terraform-control-module/template.yaml, backstage/templates/scaffolder/terraform-storage-transfer/template.yaml, backstage/templates/scaffolder/terraform-with-terragrunt/template.yaml, docs/adr/0005-recommended-tag.md, docs/adr/README.md
- **chore(templates): Curate "recommended" templates**
- **fix(cloud-run): Add template to app-config**
- **chore(templates): Consolidate "terraform" tag**
=> fix(templates): Curate "recommeded" templates

backstage/packages/backend/package.json, backstage/packages/backend/src/index.ts, backstage/yarn.lock
This plugin was missing, so scaffolder actions wouldn't work when used
---
=> fix(scaffolder): Add PagerDuty scaffolder actions plugin

backstage/packages/app/src/components/home/HomePage.tsx, catalog-info.yaml
This is intended to replace the "backstage" system.  This way,
regardless of the platform we uses, we can link it to a commpon System
---
=> chore:  Add new IDP system

.github/pull_request_template.md, backstage/templates/scaffolder/add-repo/content/.github/pull_request_template.md, backstage/templates/scaffolder/python-package/content/.github/commit_message_format_reminder.md, backstage/templates/scaffolder/terraform-cloud-run/content/.github/pull_request_template.md, backstage/templates/scaffolder/terraform-cloud-run/content/dev/.terraform-version, backstage/templates/scaffolder/terraform-cloud-run/content/mise.toml, backstage/templates/scaffolder/terraform-cloud-run/content/prod/.terraform-version, backstage/templates/scaffolder/terraform-control-module/content/dev/.terraform-version, backstage/templates/scaffolder/terraform-control-module/content/mise.toml, backstage/templates/scaffolder/terraform-control-module/content/prod/.terraform-version, backstage/templates/scaffolder/terraform-mediawiki/content/.github/pull_request_template.md, backstage/templates/scaffolder/terraform-mediawiki/content/terraform/.terraform-version, backstage/templates/scaffolder/terraform-mediawiki/content/terraform/mise.toml, backstage/templates/scaffolder/terraform-storage-transfer/content/.github/pull_request_template.md, backstage/templates/scaffolder/terraform-storage-transfer/content/mise.toml, backstage/templates/scaffolder/terraform-storage-transfer/content/prod/.terraform-version, backstage/templates/scaffolder/terraform-with-terragrunt/content/.github/pull_request_template.md
=> refactor: Remove .terraform-version files and add mise.toml for Terraform version management

deployment/dev/terraform/.envrc, deployment/dev/terraform/.terraform.lock.hcl, deployment/dev/terraform/README.md, deployment/dev/terraform/database.tf, deployment/dev/terraform/terraform.tf, deployment/prod/terraform/.envrc, deployment/prod/terraform/.terraform.lock.hcl, deployment/prod/terraform/README.md, deployment/prod/terraform/database.tf, deployment/prod/terraform/terraform.tf, docs/operations.md
Update Terraform provider versions to the latest and enhance documentation for managing environments and applying changes.
=> chore(deps): Update Terraform provider versions and documentation

backstage/app-config.production.yaml, backstage/templates/scaffolder/defaults/steps/publish.yaml
misc config changes 
fixes 
`Invalid input passed to action publish:github, instance is not allowed to have the additional property "allowedHosts"` error
=> fix: scaffolder errror

backstage/templates/BITS/systems.yaml, backstage/templates/BITS/systems/pkgbuilder.yaml
We have a ton of packages built with htis pipeline and it would be good to have them in backstage
=> feat: add pkgbuilder system configuration to Backstage

.github/workflows/publish.yaml
Creates a monthly release providing a log and listing of all the changes since the last "release" - this is more a summery that an actual release, since the features and fixes are already live, but still useful imo
=> feat: add GitHub Actions workflow for monthly release creation
